// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package grpc

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// HelloServiceClient is the client API for HelloService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type HelloServiceClient interface {
	GetValue(ctx context.Context, in *Value, opts ...grpc.CallOption) (*Value, error)
	StreamToValue(ctx context.Context, opts ...grpc.CallOption) (HelloService_StreamToValueClient, error)
	ValueToStream(ctx context.Context, in *Value, opts ...grpc.CallOption) (HelloService_ValueToStreamClient, error)
	StreamToStream(ctx context.Context, opts ...grpc.CallOption) (HelloService_StreamToStreamClient, error)
}

type helloServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewHelloServiceClient(cc grpc.ClientConnInterface) HelloServiceClient {
	return &helloServiceClient{cc}
}

func (c *helloServiceClient) GetValue(ctx context.Context, in *Value, opts ...grpc.CallOption) (*Value, error) {
	out := new(Value)
	err := c.cc.Invoke(ctx, "/HelloService/GetValue", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *helloServiceClient) StreamToValue(ctx context.Context, opts ...grpc.CallOption) (HelloService_StreamToValueClient, error) {
	stream, err := c.cc.NewStream(ctx, &HelloService_ServiceDesc.Streams[0], "/HelloService/StreamToValue", opts...)
	if err != nil {
		return nil, err
	}
	x := &helloServiceStreamToValueClient{stream}
	return x, nil
}

type HelloService_StreamToValueClient interface {
	Send(*Value) error
	CloseAndRecv() (*Value, error)
	grpc.ClientStream
}

type helloServiceStreamToValueClient struct {
	grpc.ClientStream
}

func (x *helloServiceStreamToValueClient) Send(m *Value) error {
	return x.ClientStream.SendMsg(m)
}

func (x *helloServiceStreamToValueClient) CloseAndRecv() (*Value, error) {
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	m := new(Value)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *helloServiceClient) ValueToStream(ctx context.Context, in *Value, opts ...grpc.CallOption) (HelloService_ValueToStreamClient, error) {
	stream, err := c.cc.NewStream(ctx, &HelloService_ServiceDesc.Streams[1], "/HelloService/ValueToStream", opts...)
	if err != nil {
		return nil, err
	}
	x := &helloServiceValueToStreamClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type HelloService_ValueToStreamClient interface {
	Recv() (*Value, error)
	grpc.ClientStream
}

type helloServiceValueToStreamClient struct {
	grpc.ClientStream
}

func (x *helloServiceValueToStreamClient) Recv() (*Value, error) {
	m := new(Value)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *helloServiceClient) StreamToStream(ctx context.Context, opts ...grpc.CallOption) (HelloService_StreamToStreamClient, error) {
	stream, err := c.cc.NewStream(ctx, &HelloService_ServiceDesc.Streams[2], "/HelloService/StreamToStream", opts...)
	if err != nil {
		return nil, err
	}
	x := &helloServiceStreamToStreamClient{stream}
	return x, nil
}

type HelloService_StreamToStreamClient interface {
	Send(*Value) error
	Recv() (*Value, error)
	grpc.ClientStream
}

type helloServiceStreamToStreamClient struct {
	grpc.ClientStream
}

func (x *helloServiceStreamToStreamClient) Send(m *Value) error {
	return x.ClientStream.SendMsg(m)
}

func (x *helloServiceStreamToStreamClient) Recv() (*Value, error) {
	m := new(Value)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// HelloServiceServer is the server API for HelloService service.
// All implementations must embed UnimplementedHelloServiceServer
// for forward compatibility
type HelloServiceServer interface {
	GetValue(context.Context, *Value) (*Value, error)
	StreamToValue(HelloService_StreamToValueServer) error
	ValueToStream(*Value, HelloService_ValueToStreamServer) error
	StreamToStream(HelloService_StreamToStreamServer) error
	mustEmbedUnimplementedHelloServiceServer()
}

// UnimplementedHelloServiceServer must be embedded to have forward compatible implementations.
type UnimplementedHelloServiceServer struct {
}

func (UnimplementedHelloServiceServer) GetValue(context.Context, *Value) (*Value, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetValue not implemented")
}
func (UnimplementedHelloServiceServer) StreamToValue(HelloService_StreamToValueServer) error {
	return status.Errorf(codes.Unimplemented, "method StreamToValue not implemented")
}
func (UnimplementedHelloServiceServer) ValueToStream(*Value, HelloService_ValueToStreamServer) error {
	return status.Errorf(codes.Unimplemented, "method ValueToStream not implemented")
}
func (UnimplementedHelloServiceServer) StreamToStream(HelloService_StreamToStreamServer) error {
	return status.Errorf(codes.Unimplemented, "method StreamToStream not implemented")
}
func (UnimplementedHelloServiceServer) mustEmbedUnimplementedHelloServiceServer() {}

// UnsafeHelloServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to HelloServiceServer will
// result in compilation errors.
type UnsafeHelloServiceServer interface {
	mustEmbedUnimplementedHelloServiceServer()
}

func RegisterHelloServiceServer(s grpc.ServiceRegistrar, srv HelloServiceServer) {
	s.RegisterService(&HelloService_ServiceDesc, srv)
}

func _HelloService_GetValue_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Value)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HelloServiceServer).GetValue(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/HelloService/GetValue",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HelloServiceServer).GetValue(ctx, req.(*Value))
	}
	return interceptor(ctx, in, info, handler)
}

func _HelloService_StreamToValue_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(HelloServiceServer).StreamToValue(&helloServiceStreamToValueServer{stream})
}

type HelloService_StreamToValueServer interface {
	SendAndClose(*Value) error
	Recv() (*Value, error)
	grpc.ServerStream
}

type helloServiceStreamToValueServer struct {
	grpc.ServerStream
}

func (x *helloServiceStreamToValueServer) SendAndClose(m *Value) error {
	return x.ServerStream.SendMsg(m)
}

func (x *helloServiceStreamToValueServer) Recv() (*Value, error) {
	m := new(Value)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _HelloService_ValueToStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(Value)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(HelloServiceServer).ValueToStream(m, &helloServiceValueToStreamServer{stream})
}

type HelloService_ValueToStreamServer interface {
	Send(*Value) error
	grpc.ServerStream
}

type helloServiceValueToStreamServer struct {
	grpc.ServerStream
}

func (x *helloServiceValueToStreamServer) Send(m *Value) error {
	return x.ServerStream.SendMsg(m)
}

func _HelloService_StreamToStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(HelloServiceServer).StreamToStream(&helloServiceStreamToStreamServer{stream})
}

type HelloService_StreamToStreamServer interface {
	Send(*Value) error
	Recv() (*Value, error)
	grpc.ServerStream
}

type helloServiceStreamToStreamServer struct {
	grpc.ServerStream
}

func (x *helloServiceStreamToStreamServer) Send(m *Value) error {
	return x.ServerStream.SendMsg(m)
}

func (x *helloServiceStreamToStreamServer) Recv() (*Value, error) {
	m := new(Value)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// HelloService_ServiceDesc is the grpc.ServiceDesc for HelloService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var HelloService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "HelloService",
	HandlerType: (*HelloServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetValue",
			Handler:    _HelloService_GetValue_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamToValue",
			Handler:       _HelloService_StreamToValue_Handler,
			ClientStreams: true,
		},
		{
			StreamName:    "ValueToStream",
			Handler:       _HelloService_ValueToStream_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "StreamToStream",
			Handler:       _HelloService_StreamToStream_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "internal/grpc/route.proto",
}
